### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by qlBuck** [EE-modders/Empire-Earth-Setup#1]
Hi Guys,

any chance this can be modified so the game can run on a mac through parallels with an M-Chip (ARM-Processor)? If not, maybe mention this on the website. Thank.s

**Comment by EnergyCube** [comment]
Hi @qlBuck, I recently managed to create a version of the setup that run on ARM64 on Parallels with an M1 Chip.
There is some issues to fix before releasing it officially with ARM support, I will update that issue when it's done, sadly I have an ARM device only very rarely which may delay the development of this version, but it will be done.

**Comment by qlBuck** [comment]
Wow great thanks! Looking forward to it! Keep up the good work!

**Comment by qlBuck** [comment]
Any Updates on this? Just gave it a shot again and faced the same issues... Is anyone working on this?

**Comment by EnergyCube** [comment]
Hey, the December update is coming!
Here is the video that mentions the changelog for the Setup: https://youtu.be/l9uboJHvu7c
Only a few days left if I can finalize the update!

**Comment by EnergyCube** [comment]
Hey @qlBuck, the update as been released!
I invite you to try it and get back to me :)

**Comment by qlBuck** [comment]
Hey @EnergyCube ! Thanks for the heads up! I just tried the latest version and yes - installation on my M1 Max MBP went through smoothly. 
But the graphics is messed up. Not the menu and the game interface, but the game itself (see screenshot). Any suggestions? Thanks a lot, and again: your work is so much appreciated! 
<img width="1408" alt="Screenshot 2022-12-26 at 11 07 11" src="https://user-images.githubusercontent.com/72275304/209538851-423c656e-18d3-40d2-9bf6-02a6181c8357.png">

**Comment by EnergyCube** [comment]
@qlBuck
For the bad rendering part:
Try to change EE settings  to enable or disable TnL.
If it dosn't work try to reinstall and use a DirectX Wrapper.

For the bad menu size:
Your resolution is too big for EE! Go in `dreXmod.config` and edit the `MenuSettings` setting and make `AutoDetect` to `0` and set the resolution you want in the `Resolution[...]` fields (don't go over 4k).
If you can find the exact resolution from where the game start doing that incomplete menu draw, I will implement something that will use automatically a resolution lower that that value.

**Comment by EnergyCube** [comment]
Any news @qlBuck ?

**Comment by EnergyCube** [comment]
As I've successfully tested on an M1 and an M1 Pro, I don't think there's a problem anymore.

For those who have a similar problem, you should set the **Windows resolution to 1920x1200 (or 1920x1080) and choose exactly the same in the EE settings**.
This will at least ensure that there are no resolution-related problems, such as partially displayed menus or crashes.
