### ISSUE TITLE
dreXmod.config formatting

### ISSUE THREAD

**Issue by giocic2** [EE-modders/Empire-Earth-Setup#2]
I suggest to replace the "----" limiters at the top of dreXmod.config file with underscores, so it doesn't mess with the intellisense from VScode.
![image](https://github.com/EE-modders/Empire-Earth-Setup/assets/74670040/16a19d9a-b500-4001-97a5-5ca97149e944)
![image](https://github.com/EE-modders/Empire-Earth-Setup/assets/74670040/32f0e086-f2c2-4bbd-8d58-472ed68e96b0)

**Comment by EnergyCube** [comment]
I'll probably do it in the next setup update and possibly also in the individual dreXmod 3 download archive.

**Comment by EnergyCube** [comment]
Fixed in https://github.com/EE-modders/Empire-Earth-Setup/commit/cab1babec5985002b5e3db0bacecbc5ee7ec062a, the Community Setup v1.6.1 is now available, and the dreXmod download page also provides a corrected dreXmod 3 configuration that respect XML convention.
