### ISSUE TITLE
Empire Earth Glitch

### ISSUE THREAD

**Issue by phume03** [EE-modders/Empire-Earth-Setup#3]
Hi, might be the wrong place to put this -- EE comes with plenty of manuals (https://github.com/EE-modders/Empire-Earth-toolbox/wiki) which is helpful. There is a massive glitch in the game. Can you help me investigate it further? _To look at it further myself will help me to upgrade my development skills_. 

The issue is that, in one of the campaigns, it seems that bots/units spawn randomly and attack one of my main units, thus ending the game. I noted game glitches a few campaigns back and kept playing. Since the game ends, I decided to isolate this glitch. To do that, I placed my unit behind many walls... like a maze with no exits or entry. The bad units spawn right in the "maze". So, it is that obvious!

Which tools in the EE modders repo and [toolbox](https://github.com/EE-modders/Empire-Earth-toolbox/wiki) will allow me to check the code base for such bugs (if caught again) and report or fix them? They make for bad game play.

**Comment by EnergyCube** [comment]
Hi, I'm sadly not sure to understand what is your issue.
I would recommand you to join the EE Reborn discord for futher discussion: https://discord.com/invite/BjUXbFB
If you don't have discord feel free to try to explain more clearly the issue.

**Comment by phume03** [comment]
> Hi, I'm sadly not sure to understand what is your issue. I would recommand you to join the EE Reborn discord for futher discussion: https://discord.com/invite/BjUXbFB If you don't have discord feel free to try to explain more clearly the issue.

Hey @EnergyCube , I edited for clarity -- hope you get it. Then, I no longer have a discord account. Any possibility of getting me started here (like asking for a chizel and a little direction/tutorial/guidance) and if the need arises, I can go chat some more on discord channel for the game with others in the community?

**Comment by EnergyCube** [comment]
If you are talking about the greek scenario 2, where you need escape of the island.
Well units will spawn forever until you die, it's not a glitch, is a trigger in the scenario.
If you are not talking about that, please give more information and a way to reproduce the issue.

**Comment by phume03** [comment]
Yes, I think the Minoans had no base and do spawn scouts somewhat indefinitely, they then spawn an army which kills you -- happens faster if you advance. I noted that. 

English campaign, scenario 3. The main enemy unit will not die. But they do get severely injured. That triggers an escape. They get fully healed but my army is severely reduced. So, it is quite impossible to repeat the feat. Interesting and well noted. 

Otherwise, when picking off the enemy army, the glitch occurs. My main unit gets killed behind walls (the maze) when the main/final battle starts. The English spawn anywhere where the main unit is. After the first attack, I see the second trigger to get to higher ground. However, I think I am irked by the impossible situation. The enemy units do not break down/destroy anything, they don't even move through walls or the game field; confirmed by checking the radar, you would note the yellow moving through the red (walls)!

There are other bugs, I wish to check them out.

**Comment by EnergyCube** [comment]
This is perfectly normal.

The thing you can do on the greek map is, do not stay on the island, build quickly the dock, build the transport and some ships for escape, and save 100 wood for build the capitol (stay on the island is just a trap).

For the english scenario 3 here is a message from one of the player of the community:
```
scenario 3 is about willy
is the invasion of willy to normandy
but doesn´t make sense what is saying
because the main battle is outside the walls
is the battle os hasttin
I think is confusing with the greek campaign scenario 3
that is the scenario of Troy
the buildings regenerate, speciality the walls
the idea is fight until 2 triggers are activated
the first is build a temple near a sacred place
and then will appear the troy horse
then you will put the best units inside for end the scenario
if he keeps trying to destroy the walls will not happen because there is a trigger prevent the walls are destroyed
EVEN the characters say that
maybe he is not reading the instructions to play?
```

**Comment by phume03** [comment]
That is hilarious. I completed the Greek campaign and learned all of that. Very well done puzzle. 

Another example, the player name in the main campaign menu was not saving after initial installation of the game. It got automatically fixed after I completed the Greek campaign. It had me wondering if there were automatic updates for the game. Feels like a security flaw in my system that someone can fix that on the fly, I got scared. I changed it a few dozen (literally 12) times during game play, and restarting of the application on my system. No problem though. The settings menu has a few options missing with the radio buttons, such that the graphics level might say "High", "High", "High", rather than "High", "Medium", and "Low" as an example. It actually says "A" a number of times and is preset to "custom". The legend during game play just randomly started being covered by a white block/panel. But, it does not stay. When this occurs, my CPU does not spike. So, it seems like a glitch of sorts that needs to be looked at. Common sense also informs me that the game is too low level graphics for the machine not to be rendering such parts well (no offense). So, it would help plenty if someone took a look at that at some point. 

Otherwise, I hear you on thinking that that (the gameplay glitch) is normal. Though, I doubt it very very much. It is like a mini "too perfect" assassination, following on from the plot introduction or scenario 2. But, it does trigger a secondary event. I think that it would have been well done, if it was triggered by the main character/unit being left defenseless and then getting killed. The bandits (purple units) also spawned inside a wall I setup on the southern shore. Well enough, the first attack could have come from offscreen, to the East of Willy's base as in the Greek scenario you brought up. But the second attack, nearer to the bandit camp unfortunately happened after I setup a wall, and so those units should have spawned outside the wall. I got very curious and looked up the game a little more, and it seems work on it is open sourced. So, I do wish to take a look at these parts. This last part does not end gameplay, but the first (assassination) does. 

I will wait to hear what others have to say in the comments after us. Thank you for trying @EnergyCube .

P.s. this game reminds me of **Age of Empires I**, on Windows 98, which will not run on modern systems at all. So, great stuff! _Willy must live <3_

**Comment by EnergyCube** [comment]
Closing due to the discovery of a parallel universe where the issue has never been opened.

**Comment by phume03** [comment]
> Closing due to the discovery of a parallel universe where the issue has never been opened.

Why did you close the issue(s)? I read End-User License Agreement (EULA) parts; 3A, 5, and 7, which state:
 
>	(3). Responsibilities of End User: A. Subject to the Grant of License hereinabove, you may not, in whole or in part, copy, photocopy, reproduce, translate, reverse engineer, derive source code, modify, disassemble, decompile, create derivative works based on the Program, or remove any proprietary notices or labels on the Program without the prior consent, in writing, of Sierra.
> 		
> 	(5). Termination. This License Agreement is effective until terminated. You may terminate the License Agreement at any time by destroying the Program. Sierra may, at its discretion, terminate this License Agreement in the event that you fail to comply with the terms and conditions contained herein. In such event, you must immediately destroy the Program. 
> 
> 	(7). Limited Warranty. Sierra expressly disclaims any warranty for the Program, Editor and Manual(s). The Program, Editor and Manual(s) are provided "as is" without warranty of any kind, either express or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, or noninfringement. The entire risk arising out of use or performance of the Program and Manual(s) remains with the User, however Sierra warrants up to and including 90 days from the date of your purchase of the Program that the media containing the Program shall be free from defects in material and workmanship. In the event that the media proves to be defective during that time period, and upon presentation to Sierra of proof of purchase of the defective Program, Sierra will at its option 1) correct any defect, 2) provide you with a product of equal or lesser value, or 3) refund your money. Some states do not allow the exclusion or limitation of implied warranties or liability for incidental damages, so the above limitations may not apply to you.


I also found a few readme files which list some if not all of the issues that I listed above in my initial report, including something about a freezing mouse pointer, which I experienced myself but just left out of this issue request. These are in parts 2 and 3 of the readme titled:

> II. GENERAL TECHNICAL ISSUES
> III.	GENERAL GAME ISSUES (Including updated game play information)

Anyway.

**Comment by EnergyCube** [comment]
This issue is closed because it is not related to the Setup.
The game source code don't exist anymore, any low level modification require reverse engineering skills.
If you have some feel free to try and communicate about it on Discord and not here, this is the game setup Github page.
